/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Practica7;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Italo
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Album = new javax.swing.JTabbedPane();
        Autor = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        ItemOpen = new javax.swing.JMenuItem();
        ItemClose = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        ItemExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Autor.setText("Hecho por Italo Garleni");

        MenuFile.setText("File");

        ItemOpen.setText("Open");
        ItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemOpenActionPerformed(evt);
            }
        });
        MenuFile.add(ItemOpen);

        ItemClose.setText("Close");
        ItemClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemCloseActionPerformed(evt);
            }
        });
        MenuFile.add(ItemClose);
        MenuFile.add(jSeparator1);

        ItemExit.setText("Exit");
        ItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemExitActionPerformed(evt);
            }
        });
        MenuFile.add(ItemExit);

        Menu.add(MenuFile);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Album)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Autor)
                .addGap(0, 290, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Album, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addGap(17, 17, 17)
                .addComponent(Autor))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemOpenActionPerformed
        // TODO add your handling code here:
        JFileChooser filechooser = new JFileChooser();
        filechooser.setCurrentDirectory(null);
        ImageFilter filter = new ImageFilter();
        filechooser.addChoosableFileFilter(filter);
        filechooser.setFileFilter(filter);
        
        int retorno = filechooser.showOpenDialog(this);
        if (retorno == JFileChooser.APPROVE_OPTION){
            File file = filechooser.getSelectedFile();
            String filename = file.getName();
            Practica7.VisorImagen visor = new VisorImagen();
            visor.setImagen(file);
            Album.add(filename,visor);
        }
    }//GEN-LAST:event_ItemOpenActionPerformed

    private void ItemCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemCloseActionPerformed
        // TODO add your handling code here:
        int index = Album.getSelectedIndex();
        if (index != -1)
            Album.removeTabAt(index);
    }//GEN-LAST:event_ItemCloseActionPerformed

    private void ItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ItemExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Album;
    private javax.swing.JLabel Autor;
    private javax.swing.JMenuItem ItemClose;
    private javax.swing.JMenuItem ItemExit;
    private javax.swing.JMenuItem ItemOpen;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu MenuFile;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
