/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Practica6;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.AdjustmentEvent;
import javax.swing.JScrollBar;
import javax.swing.JViewport;

/**
 *
 * @author Italo
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        Dimension Idimension = Imagen.getSize();
        Iancho = Idimension.width;
        Ialto = Idimension.height;
        TextIAlto.setText(String.valueOf(Ialto));
        TextIAncho.setText(String.valueOf(Iancho));
        
        vista = Scroll.getViewport();
        Dimension Vdimension = vista.getExtentSize();
        Vancho = Vdimension.width;
        Valto = Vdimension.height;
        TextValto.setText(String.valueOf(Valto));
        TextVancho.setText(String.valueOf(Vancho));
        Point p = vista.getViewPosition();
        Vx = p.x;
        Vy = p.y;
        TextVX.setText(String.valueOf(Vx));
        TextVY.setText(String.valueOf(Vy));
        Hbar = Scroll.getHorizontalScrollBar();
        Vbar = Scroll.getVerticalScrollBar();
        Hbar.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            @Override
            public void adjustmentValueChanged(AdjustmentEvent e) {
                HScrollAdjust(e);
            }
        });
        Vbar.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            @Override
            public void adjustmentValueChanged(AdjustmentEvent e) {
                VScrollAdjust(e);
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Scroll = new javax.swing.JScrollPane();
        Imagen = new javax.swing.JLabel();
        Autor = new javax.swing.JLabel();
        DatoImage = new javax.swing.JPanel();
        LabelAncho = new javax.swing.JLabel();
        TextIAncho = new javax.swing.JTextField();
        TextIAlto = new javax.swing.JTextField();
        LabelAlto = new javax.swing.JLabel();
        DatoCursor = new javax.swing.JPanel();
        LabelEstado = new javax.swing.JLabel();
        CE = new javax.swing.JTextField();
        LabelX = new javax.swing.JLabel();
        CX = new javax.swing.JTextField();
        LabelY = new javax.swing.JLabel();
        CY = new javax.swing.JTextField();
        DatoViewport = new javax.swing.JPanel();
        Ancho = new javax.swing.JLabel();
        TextVancho = new javax.swing.JTextField();
        Alto = new javax.swing.JLabel();
        TextValto = new javax.swing.JTextField();
        PosX = new javax.swing.JLabel();
        TextVX = new javax.swing.JTextField();
        PosY = new javax.swing.JLabel();
        TextVY = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Scroll.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                ScrollComponentResized(evt);
            }
        });

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Practica6/setas1.jpg"))); // NOI18N
        Imagen.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ImagenMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ImagenMouseMoved(evt);
            }
        });
        Imagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ImagenMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ImagenMouseReleased(evt);
            }
        });
        Scroll.setViewportView(Imagen);

        Autor.setText("Hecho por Italo Garleni");

        DatoImage.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LabelAncho.setText("Ancho");
        LabelAncho.setToolTipText("");

        LabelAlto.setText("Alto");

        javax.swing.GroupLayout DatoImageLayout = new javax.swing.GroupLayout(DatoImage);
        DatoImage.setLayout(DatoImageLayout);
        DatoImageLayout.setHorizontalGroup(
            DatoImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatoImageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatoImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelAncho)
                    .addComponent(LabelAlto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(DatoImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextIAncho, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(TextIAlto))
                .addContainerGap())
        );
        DatoImageLayout.setVerticalGroup(
            DatoImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatoImageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatoImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAncho)
                    .addComponent(TextIAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DatoImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextIAlto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelAlto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DatoCursor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LabelEstado.setText("Estado");

        LabelX.setText("Pos X");

        LabelY.setText("Pos Y");

        javax.swing.GroupLayout DatoCursorLayout = new javax.swing.GroupLayout(DatoCursor);
        DatoCursor.setLayout(DatoCursorLayout);
        DatoCursorLayout.setHorizontalGroup(
            DatoCursorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatoCursorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatoCursorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatoCursorLayout.createSequentialGroup()
                        .addComponent(LabelEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CE, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DatoCursorLayout.createSequentialGroup()
                        .addComponent(LabelX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CX, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DatoCursorLayout.createSequentialGroup()
                        .addComponent(LabelY)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CY, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        DatoCursorLayout.setVerticalGroup(
            DatoCursorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatoCursorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatoCursorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEstado)
                    .addComponent(CE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DatoCursorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelX)
                    .addComponent(CX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DatoCursorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelY)
                    .addComponent(CY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DatoViewport.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Ancho.setText("Ancho");

        Alto.setText("Alto");

        PosX.setText("Pos X");

        PosY.setText("Pos Y");

        javax.swing.GroupLayout DatoViewportLayout = new javax.swing.GroupLayout(DatoViewport);
        DatoViewport.setLayout(DatoViewportLayout);
        DatoViewportLayout.setHorizontalGroup(
            DatoViewportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatoViewportLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatoViewportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatoViewportLayout.createSequentialGroup()
                        .addComponent(Ancho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addComponent(TextVancho, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DatoViewportLayout.createSequentialGroup()
                        .addComponent(Alto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextValto, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DatoViewportLayout.createSequentialGroup()
                        .addComponent(PosX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextVX, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DatoViewportLayout.createSequentialGroup()
                        .addComponent(PosY)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextVY, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        DatoViewportLayout.setVerticalGroup(
            DatoViewportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatoViewportLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatoViewportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ancho)
                    .addComponent(TextVancho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DatoViewportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alto)
                    .addComponent(TextValto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DatoViewportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PosX)
                    .addComponent(TextVX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DatoViewportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextVY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PosY))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DatoImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DatoCursor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DatoViewport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Autor)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DatoImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DatoCursor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DatoViewport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Autor)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImagenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenMousePressed
        // TODO add your handling code here:
        Imagen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CE.setText("Presionado");
        
        Point posicion = Imagen.getMousePosition();
        Cx0 = posicion.x;
        Cy0 = posicion.y;
        p0 = vista.getViewPosition();
    }//GEN-LAST:event_ImagenMousePressed

    private void ImagenMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenMouseReleased
        // TODO add your handling code here:
        Imagen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CE.setText("");
    }//GEN-LAST:event_ImagenMouseReleased

    private void ImagenMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenMouseDragged
        // TODO add your handling code here:
        CE.setText("Arrastrado");
        Point posicion = Imagen.getMousePosition();
        Cx = posicion.x;
        Cy = posicion.y;
        CX.setText(String.valueOf(Cx));
        CY.setText(String.valueOf(Cy));
        
        Point p = vista.getViewPosition();
        p.x = p0.x - (int)((Cx-Cx0)/1.5);
        p.y = p0.y - (int)((Cy-Cy0)/1.5);
        if (p.x < 0) p.x = 0;
        if (p.x > Iancho-Vancho) p.x = Iancho - Vancho;
        if (p.y < 0) p.y = 0;
        if (p.y > Ialto-Valto) p.y = Ialto - Valto;
        vista.setViewPosition(p);
    }//GEN-LAST:event_ImagenMouseDragged

    private void ImagenMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenMouseMoved
        // TODO add your handling code here:
        Point posicion = Imagen.getMousePosition();
        Cx = posicion.x;
        Cy = posicion.y;
        CX.setText(String.valueOf(Cx));
        CY.setText(String.valueOf(Cy));
    }//GEN-LAST:event_ImagenMouseMoved

    private void ScrollComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ScrollComponentResized
        // TODO add your handling code here:
        Dimension Vdimension = vista.getExtentSize();
        Vancho = Vdimension.width;
        Valto = Vdimension.height;
        TextValto.setText(String.valueOf(Valto));
        TextVancho.setText(String.valueOf(Vancho));
    }//GEN-LAST:event_ScrollComponentResized

    private void HScrollAdjust(java.awt.event.AdjustmentEvent e){
        Point p = vista.getViewPosition();
        Vx = p.x;
        TextVX.setText(String.valueOf(Vx));
    }
    
    private void VScrollAdjust (java.awt.event.AdjustmentEvent e){
        Point p = vista.getViewPosition();
        Vy = p.y;
        TextVY.setText(String.valueOf(Vy));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alto;
    private javax.swing.JLabel Ancho;
    private javax.swing.JLabel Autor;
    private javax.swing.JTextField CE;
    private javax.swing.JTextField CX;
    private javax.swing.JTextField CY;
    private javax.swing.JPanel DatoCursor;
    private javax.swing.JPanel DatoImage;
    private javax.swing.JPanel DatoViewport;
    private javax.swing.JLabel Imagen;
    private javax.swing.JLabel LabelAlto;
    private javax.swing.JLabel LabelAncho;
    private javax.swing.JLabel LabelEstado;
    private javax.swing.JLabel LabelX;
    private javax.swing.JLabel LabelY;
    private javax.swing.JLabel PosX;
    private javax.swing.JLabel PosY;
    private javax.swing.JScrollPane Scroll;
    private javax.swing.JTextField TextIAlto;
    private javax.swing.JTextField TextIAncho;
    private javax.swing.JTextField TextVX;
    private javax.swing.JTextField TextVY;
    private javax.swing.JTextField TextValto;
    private javax.swing.JTextField TextVancho;
    // End of variables declaration//GEN-END:variables
    private int Iancho, Ialto;
    private int Cx, Cy;
    
    private JViewport vista;
    private int Vancho, Valto, Vx, Vy;
    private JScrollBar Hbar, Vbar;
    
    private int Cx0, Cy0;
    private Point p0;
}
