/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Practica5;

import java.awt.Point;
import java.awt.Rectangle;

/**
 *
 * @author usuario
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Autor = new javax.swing.JLabel();
        Capas = new javax.swing.JLayeredPane();
        Panel1 = new javax.swing.JPanel();
        Panel2 = new javax.swing.JPanel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Autor.setText("Hecho por Italo Garleni");

        Capas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel1.setBackground(new java.awt.Color(0, 0, 255));
        Panel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Panel1MouseDragged(evt);
            }
        });
        Panel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Panel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Panel1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Capas.add(Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        Panel2.setBackground(new java.awt.Color(0, 255, 0));
        Panel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Panel2MouseDragged(evt);
            }
        });
        Panel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Panel2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Panel2MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        Capas.add(Panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 190, 160));

        Fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Practica5/Torino_panorama_Superga.jpg"))); // NOI18N
        Fondo.setToolTipText("");
        Capas.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Capas)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Autor)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Capas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Autor)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Panel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel1MousePressed
        // TODO add your handling code here:
        
        Capas.moveToFront(Panel1);
        
        Rectangle r = Capas.getBounds();
        Wbox = r.width;
        Hbox = r.height;
        r = Panel1.getBounds();
        Wpanel1 = r.width;
        Hpanel1 = r.height;
        
        Xpanel1_0 = r.x;
        Ypanel1_0 = r.y;
        
        Point p = Capas.getMousePosition();
        Xmouse_0 = p.x;
        Ymouse_0 = p.y;
        
        Panel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_Panel1MousePressed

    private void Panel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel1MouseDragged
        // TODO add your handling code here:
        Point p = Capas.getMousePosition();
        
        int Xpanel1 = Xpanel1_0 + p.x - Xmouse_0;
        int Ypanel1 = Ypanel1_0 + p.y - Ymouse_0;
        
        if (Xpanel1 < 0) Xpanel1 = 0;
        if (Ypanel1 < 0) Ypanel1 = 0;
        
        int Xmax = Wbox - Wpanel1;
        int Ymax = Hbox - Hpanel1;
        if (Xpanel1 > Xmax) Xpanel1 = Xmax;
        if (Ypanel1 > Ymax) Ypanel1 = Ymax;
        
        p.x = Xpanel1;
        p.y = Ypanel1;
        Panel1.setLocation(p);
    }//GEN-LAST:event_Panel1MouseDragged

    private void Panel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel1MouseReleased
        // TODO add your handling code here:
        Panel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

    }//GEN-LAST:event_Panel1MouseReleased

    private void Panel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel2MousePressed
        // TODO add your handling code here:
        
        Capas.moveToFront(Panel2);
        
        Rectangle r = Capas.getBounds();
        Wbox = r.width;
        Hbox = r.height;
        r = Panel2.getBounds();
        Wpanel2 = r.width;
        Hpanel2 = r.height;
        
        Xpanel2_0 = r.x;
        Ypanel2_0 = r.y;
        
        Point p = Capas.getMousePosition();
        Xmouse_0 = p.x;
        Ymouse_0 = p.y;
        
        Panel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_Panel2MousePressed

    private void Panel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel2MouseDragged
        // TODO add your handling code here:
        Point p = Capas.getMousePosition();
        
        int Xpanel2 = Xpanel2_0 + p.x - Xmouse_0;
        int Ypanel2 = Ypanel2_0 + p.y - Ymouse_0;
        
        if (Xpanel2 < 0) Xpanel2 = 0;
        if (Ypanel2 < 0) Ypanel2 = 0;
        
        int Xmax = Wbox - Wpanel2;
        int Ymax = Hbox - Hpanel2;
        if (Xpanel2 > Xmax) Xpanel2 = Xmax;
        if (Ypanel2 > Ymax) Ypanel2 = Ymax;
        
        p.x = Xpanel2;
        p.y = Ypanel2;
        Panel2.setLocation(p);
    }//GEN-LAST:event_Panel2MouseDragged

    private void Panel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel2MouseReleased
        // TODO add your handling code here:
        Panel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_Panel2MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Autor;
    private javax.swing.JLayeredPane Capas;
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    // End of variables declaration//GEN-END:variables
    
    //Variables del tamaño del Panel1, Panel2 y el JlayeredPane
    int Wbox, Hbox, Wpanel1, Hpanel1, Wpanel2, Hpanel2;
    
    //variables del ratón y los paneles durante el movimiento
    int Xpanel1_0, Ypanel1_0, Xpanel2_0, Ypanel2_0, Xmouse_0, Ymouse_0;
}
