/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Practica8;

import javax.swing.JOptionPane;

/**
 *
 * @author Italo
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        BotonLogin.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogoLogin = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        BotonLoginAceptar = new javax.swing.JButton();
        BotonLoginCancelar = new javax.swing.JButton();
        Password3 = new javax.swing.JPasswordField();
        FallosLabel = new javax.swing.JLabel();
        FallosField = new javax.swing.JTextField();
        DialogoRegister = new javax.swing.JDialog();
        SetLabel = new javax.swing.JLabel();
        RepeatLabel = new javax.swing.JLabel();
        BotonRegisterAceptar = new javax.swing.JButton();
        BotonRegisterCancelar = new javax.swing.JButton();
        Password1 = new javax.swing.JPasswordField();
        Password2 = new javax.swing.JPasswordField();
        Autor = new javax.swing.JLabel();
        Acciones = new javax.swing.JPanel();
        BotonLogin = new javax.swing.JButton();
        BotonRegister = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Estado = new javax.swing.JPanel();
        LabelRegistrado = new javax.swing.JLabel();
        LabelLogin = new javax.swing.JLabel();
        EstadoRegistrado = new javax.swing.JTextField();
        EstadoLogin = new javax.swing.JTextField();

        DialogoLogin.setMinimumSize(new java.awt.Dimension(206, 100));

        jLabel1.setText("Password:");

        BotonLoginAceptar.setText("Aceptar");
        BotonLoginAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLoginAceptarActionPerformed(evt);
            }
        });

        BotonLoginCancelar.setText("Cancelar");
        BotonLoginCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLoginCancelarActionPerformed(evt);
            }
        });

        FallosLabel.setText("Número de fallos:");

        javax.swing.GroupLayout DialogoLoginLayout = new javax.swing.GroupLayout(DialogoLogin.getContentPane());
        DialogoLogin.getContentPane().setLayout(DialogoLoginLayout);
        DialogoLoginLayout.setHorizontalGroup(
            DialogoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogoLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DialogoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogoLoginLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Password3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogoLoginLayout.createSequentialGroup()
                        .addComponent(BotonLoginAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonLoginCancelar))
                    .addGroup(DialogoLoginLayout.createSequentialGroup()
                        .addComponent(FallosLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FallosField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        DialogoLoginLayout.setVerticalGroup(
            DialogoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogoLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DialogoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Password3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DialogoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FallosLabel)
                    .addComponent(FallosField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(DialogoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonLoginAceptar)
                    .addComponent(BotonLoginCancelar))
                .addContainerGap())
        );

        DialogoRegister.setMinimumSize(new java.awt.Dimension(225, 102));

        SetLabel.setText("Set Password:");

        RepeatLabel.setText("Repeat Password:");

        BotonRegisterAceptar.setText("Aceptar");
        BotonRegisterAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegisterAceptarActionPerformed(evt);
            }
        });

        BotonRegisterCancelar.setText("Cancelar");
        BotonRegisterCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegisterCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DialogoRegisterLayout = new javax.swing.GroupLayout(DialogoRegister.getContentPane());
        DialogoRegister.getContentPane().setLayout(DialogoRegisterLayout);
        DialogoRegisterLayout.setHorizontalGroup(
            DialogoRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogoRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DialogoRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DialogoRegisterLayout.createSequentialGroup()
                        .addComponent(BotonRegisterAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(BotonRegisterCancelar))
                    .addGroup(DialogoRegisterLayout.createSequentialGroup()
                        .addGroup(DialogoRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RepeatLabel)
                            .addComponent(SetLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DialogoRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Password1)
                            .addComponent(Password2))))
                .addContainerGap())
        );
        DialogoRegisterLayout.setVerticalGroup(
            DialogoRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogoRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DialogoRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SetLabel)
                    .addComponent(Password1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DialogoRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RepeatLabel)
                    .addComponent(Password2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DialogoRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonRegisterAceptar)
                    .addComponent(BotonRegisterCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Autor.setText("Hecho por Italo Garleni");

        Acciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));
        Acciones.setToolTipText("");
        Acciones.setName(""); // NOI18N

        BotonLogin.setText("Login");
        BotonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLoginActionPerformed(evt);
            }
        });

        BotonRegister.setText("Register");
        BotonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegisterActionPerformed(evt);
            }
        });

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AccionesLayout = new javax.swing.GroupLayout(Acciones);
        Acciones.setLayout(AccionesLayout);
        AccionesLayout.setHorizontalGroup(
            AccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(BotonRegister)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AccionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Exit)
                .addGap(60, 60, 60))
        );
        AccionesLayout.setVerticalGroup(
            AccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccionesLayout.createSequentialGroup()
                .addGroup(AccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonLogin)
                    .addComponent(BotonRegister))
                .addGap(18, 18, 18)
                .addComponent(Exit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Estado.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado"));

        LabelRegistrado.setText("Registrado:");

        LabelLogin.setText("Login:");

        javax.swing.GroupLayout EstadoLayout = new javax.swing.GroupLayout(Estado);
        Estado.setLayout(EstadoLayout);
        EstadoLayout.setHorizontalGroup(
            EstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelRegistrado)
                    .addComponent(LabelLogin))
                .addGap(18, 18, 18)
                .addGroup(EstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EstadoLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(EstadoRegistrado))
                .addContainerGap())
        );
        EstadoLayout.setVerticalGroup(
            EstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelRegistrado)
                    .addComponent(EstadoRegistrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(EstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelLogin, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EstadoLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Autor)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Acciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Estado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Acciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(Autor)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int retorno = JOptionPane.showConfirmDialog(null, 
                "¿Realmente desea salir?", "Salir", JOptionPane.YES_NO_OPTION);
        
        if(retorno == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void BotonRegisterAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegisterAceptarActionPerformed
        // TODO add your handling code here:
        pass1 = String.valueOf(Password1.getPassword());
        
        String pass2 = String.valueOf(Password2.getPassword());
        Password1.setText(null);
        Password2.setText(null);
        if(!pass1.equals(pass2)){
            JOptionPane.showMessageDialog(null, "Las Passwords son diferentes\nInténtalo de nuevo",
                    "Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
            EstadoRegistrado.setText("SI");
            DialogoRegister.setVisible(false);
            BotonLogin.setEnabled(true);
        }
    }//GEN-LAST:event_BotonRegisterAceptarActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        int retorno = JOptionPane.showConfirmDialog(null, 
                "¿Realmente desea salir?", "Salir", JOptionPane.YES_NO_OPTION);
        
        if(retorno == 0){
            System.exit(0);
        }

    }//GEN-LAST:event_ExitActionPerformed

    private void BotonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegisterActionPerformed
        // TODO add your handling code here:
        DialogoRegister.setVisible(true);
    }//GEN-LAST:event_BotonRegisterActionPerformed

    private void BotonRegisterCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegisterCancelarActionPerformed
        // TODO add your handling code here:
        DialogoRegister.setVisible(false);
    }//GEN-LAST:event_BotonRegisterCancelarActionPerformed

    private void BotonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLoginActionPerformed
        // TODO add your handling code here:
        if(isLogin){
            int retorno = JOptionPane.showConfirmDialog(null,
                    "¿Realmente desea hacer Logout?", "Logout", JOptionPane.YES_NO_OPTION);
            if(retorno == 0){
                isLogin = false;
                BotonLogin.setText("LogIn");
                EstadoLogin.setText("NO");
                BotonRegister.setEnabled(true);
            }
        }
        else{
            DialogoLogin.setVisible(true);
        }
    }//GEN-LAST:event_BotonLoginActionPerformed

    private void BotonLoginCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLoginCancelarActionPerformed
        // TODO add your handling code here:
        DialogoLogin.setVisible(false);
    }//GEN-LAST:event_BotonLoginCancelarActionPerformed

    private void BotonLoginAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLoginAceptarActionPerformed
        // TODO add your handling code here:
        
        String pass3 = String.valueOf(Password3.getPassword());
        Password3.setText(null);
        if(pass3.equals(pass1)){
            EstadoLogin.setText("SI");
            isLogin = true;
            DialogoLogin.setVisible(false);
            BotonLogin.setText("LogOut");
            fallos = 0;
            BotonRegister.setEnabled(false);
        }
        else{
            JOptionPane.showMessageDialog(null, 
                    "La Password es incorrecta\nInténtalo de nuevo", "Error", JOptionPane.ERROR_MESSAGE);
            fallos++;
            FallosField.setText(String.valueOf(fallos));
        }
    }//GEN-LAST:event_BotonLoginAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Acciones;
    private javax.swing.JLabel Autor;
    private javax.swing.JButton BotonLogin;
    private javax.swing.JButton BotonLoginAceptar;
    private javax.swing.JButton BotonLoginCancelar;
    private javax.swing.JButton BotonRegister;
    private javax.swing.JButton BotonRegisterAceptar;
    private javax.swing.JButton BotonRegisterCancelar;
    private javax.swing.JDialog DialogoLogin;
    private javax.swing.JDialog DialogoRegister;
    private javax.swing.JPanel Estado;
    private javax.swing.JTextField EstadoLogin;
    private javax.swing.JTextField EstadoRegistrado;
    private javax.swing.JButton Exit;
    private javax.swing.JTextField FallosField;
    private javax.swing.JLabel FallosLabel;
    private javax.swing.JLabel LabelLogin;
    private javax.swing.JLabel LabelRegistrado;
    private javax.swing.JPasswordField Password1;
    private javax.swing.JPasswordField Password2;
    private javax.swing.JPasswordField Password3;
    private javax.swing.JLabel RepeatLabel;
    private javax.swing.JLabel SetLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    private String pass1;
    private boolean isLogin=false;
    private int fallos = 0;
}
